name: Sync Charmstore Credentials

on: 
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: 'true/false whether to run action in dry-run mode'
        required: true
        default: 'true'

jobs:
  sync_charmstore_credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.5.0
        with:
          SECRETS: |
            ^CHARMSTORE_CREDENTIAL$
            ^CHARMCRAFT_CREDENTIALS$
          REPOSITORIES: |
            ^canonical/admission-webhook-operator$
            ^canonical/argo-operators$
            ^canonical/dex-auth-operator$
            ^canonical/envoy-operator$
            ^canonical/kfp-operators$
            ^canonical/kfserving-operator$
            ^canonical/kubeflow-dashboard-operator$
            ^canonical/kubeflow-profiles-operator$
            ^canonical/kubeflow-volumes-operator$
            ^canonical/minio-operator$
            ^canonical/mlflow-operator$
            ^canonical/mlmd-operator$
            ^canonical/notebook-operators$
            ^canonical/oidc-gatekeeper-operator$
            ^canonical/pytorch-operator$
            ^canonical/seldon-core-operator$
            ^canonical/tfjob-operator$
            ^canonical/charm-tf-serving$
            ^canonical/bundle-cert-manager$
            ^canonical/bundle-istio$
            ^canonical/bundle-kubeflow$
          DRY_RUN: ${{ github.event.inputs.DRY_RUN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          CONCURRENCY: 10
        env:
          CHARMSTORE_CREDENTIAL: ${{ secrets.CHARMSTORE_CREDENTIAL }}
